# ML Assignment 1 - Reference solutions

In [1]:
import numpy as np

Creating numpy arrays

In [2]:
a = np.array([1., 1., 0.])

b = np.array([-1. ,2. ,5.])

M = np.array([[2. ,-1., 0.],
            [-1. ,2. ,-1.],
            [0. ,-1. ,2.]])

a) Compute and print the inner product between a and b.

In [3]:
print(np.dot(a,b))

1.0


b) Compute and print the matrix-vector product between M and b.

In [4]:
print(np.dot(M,b))

[-4.  0.  8.]


c) Compute and print the l2 norm of b.

L2 norm of a vector is defined as the square root of the sum of the squares of its values. For a 1d vector b, it can be calculated as square root of b(transpose).b = dot product of vector by itself

In [5]:
print(np.sqrt(np.dot(b,b)))

5.477225575051661


d) Compute and print the solution x of the linear system of equations Mx = b using the LU factorization.

Most Linear Algebra functions are present in numpy.linalg library. Ones not covered by it can be found in scipy.linalg library which is an extension of the former. The documentation for both is comprehensive with examples.

We will use scipy.linalg to solve the system of linear equations.

In [6]:
import scipy.linalg as la

In [7]:
#Factorize matrix M into upper and lower triangular matrices.
#If you observe the result of the factorization, you should have questions!
#Please go through the documentation to understand the results.

LU = la.lu_factor(M)
print(LU)

(array([[ 2.        , -1.        ,  0.        ],
       [-0.5       ,  1.5       , -1.        ],
       [ 0.        , -0.66666667,  1.33333333]]), array([0, 1, 2], dtype=int32))


In [8]:
#Use the LU factors to solve the system
x = la.lu_solve(LU,b)
print(x)

[1.5 4.  4.5]


In [9]:
#Finally cross check if x is a solution for the system (Mx = b)
np.allclose(np.dot(M,x), b)

True

e) Compute and print the the solution x of the linear system of equationsMx = b using the Cholesky factorization.

In [10]:
#Decompose the matrix into Cholesky factors M=LL*
#Again, please check documentation to understand the results
c, low = la.cho_factor(M)
c

array([[ 1.41421356, -0.70710678,  0.        ],
       [-1.        ,  1.22474487, -0.81649658],
       [ 0.        , -1.        ,  1.15470054]])

In [11]:
#Solve the system using cholesky factors
x = la.cho_solve((c, low), b)
x

array([1.5, 4. , 4.5])

Notice, we get the same solution as before.